name: deploy-main

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
  workflow_run:
    workflows: [update-main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: src

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install --prefix lat

      - name: Cache build dependencies and artifacts
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            main/node_modules
          key: main

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - run: node lat deploy main --cf-prod --yes
